version: '3'
services: 
  redis:
    image: redis:4.0.11
    ports:
      - 6399:6379
  web:
    depends_on:
      - redis
    links:
      - redis
    image: ip-rate-limit:0.1.0
    build: .
    env_file: .env
    ports:
      - 5099:5000